config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'profiles#index'

  resources :profiles do
    collection do
      get :download_file
    end
  end

end

app/models/backup_file.rb
class BackupFile < ActiveRecord::Base
  mount_uploader :file, RecordUploader

  belongs_to :profile
  has_many :versions
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_many :profile_details, dependent: :destroy
  has_many :backup_files, dependent: :destroy

  validate :check_file_or_directory

  after_create :backup_records
  after_update :update_records

  private
    def check_file_or_directory
      unless (Dir.entries(self.folders) rescue false)
        errors.add("Error", ": No such file or directory" )
      end
    end

    def backup_records
      profile_detail = self.profile_details.create
      BackupGenerator::Process.backup(self.id, self.folders, self.exclusion, 'create', profile_detail.id)
    end

    def update_records
      profile_detail = self.profile_details.create
      self.backup_files.update_all(is_new: nil) if self.backup_files.present?
      BackupGenerator::Process.backup(self.id, self.folders, self.exclusion, 'update', profile_detail.id)
    end
end

app/models/profile_detail.rb
class ProfileDetail < ActiveRecord::Base
  belongs_to :profile
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/version.rb
class Version < ActiveRecord::Base
  mount_uploader :file, RecordUploader
  
  belongs_to :backup_file
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  def index
    @profiles = Profile.all

    redirect_to new_profile_path if @profiles.size == 0
  end

  def new
    @profile = Profile.new
  end

  def create
    profile = Profile.new(profile_params)

    if profile.save
      redirect_to profiles_path, :flash => { :notice => "Succeed to create profile" }
    else
      redirect_to new_profile_path, :flash => { :error => profile.errors.full_messages.join(', ') }
    end
  end

  def edit
  end

  def update
    if @profile.save
      redirect_to profiles_path, :flash => { :notice => "Succeed to update profile" }
    else
      redirect_to edit_profile_path(@profile), :flash => { :error => @profile.errors.full_messages.join(', ') }
    end
  end

  def download_file
    send_file Version.find_by(id: params[:id]).file.path
  end

  private
    def profile_params
      params.require(:profile).permit(:name, :folders, :exclusion)
    end

    def set_profile      
      @profile = Profile.includes(:profile_details, backup_files:[:versions]).find_by(id: params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_identity
    current_user.name? ? current_user.name : current_user.email
  end

  def navbar_active_class(controller)
    css = ""

    css = "active" if controller == params[:controller]
  end
end

app/helpers/form_helper.rb
module FormHelper

  def cancel_button(path)
    link_to 'Cancel', path,
      class: 'btn btn-default'
  end

  def save_button
    content_tag :button, type: 'submit', class: 'btn btn-primary' do
      'BackUp'
    end
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Backup Data Storage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">
          <span class="glyphicon glyphicon-duplicate" aria-hidden="true"></span>
          Backup Data Storage
        </a>
      </div>
      <ul class="nav navbar-nav">
        <li class="<%= navbar_active_class('profiles') %>">
          <%= link_to "Profiles", profiles_path %>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <%= link_to "#{user_identity} <span class='caret'></span>".html_safe, '', class: 'dropdown-toggle', title: '', data: { toggle: 'dropdown' } %>
          <ul class="dropdown-menu">
            <li>
              <%= link_to "<span class='glyphicon glyphicon-log-out'></span> Sign out".html_safe, destroy_user_session_path, :method => :delete %>
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </nav>
  <% end %>

  <%= render 'layouts/messages' %>
  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/profiles/_form.html.erb
<div class="col-md-6">
  <%= form_for @profile, html: {class: 'form-horizontal'} do |f| %>
    <div class="form-group">
      <label class="col-sm-4 control-label">Profile Name</label>
      <div class="col-sm-8">
        <%= f.text_field :name, class: 'form-control', placeholder: 'Name' %>
      </div>
    </div>
    <% if params[:action] == 'new' %>
    <div class="form-group">
      <label class="col-sm-4 control-label">Which Folder(s)</label>
      <div class="col-sm-8">
        <%= f.text_field :folders, class: 'form-control', placeholder: '/home/backup-folders' %>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-4 control-label">Exclusion Folder(s)</label>
      <div class="col-sm-8">
        <%= f.text_field :exclusion, class: 'form-control', placeholder: '/home/exclusion-folder' %>
      </div>
    </div>
    <% end %>

    <div class="pull-right">
      <%= cancel_button(profiles_path) %>
      <%= save_button %>
    </div>
  <% end %>
</div>

app/views/profiles/edit.html.erb
<%= render 'form' %>

app/views/profiles/index.html.erb
<div class="col-md-6">
<%= link_to "New Profile", new_profile_path, class: 'btn btn-default btn-lg pull-right' %>
<table class="table table-striped">
  <thead>
    <tr>
      <th width="10%">No</th>
      <th>Name</th>
      <th width="20%">&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @profiles.each_with_index do |profile, index| %>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= profile.name %></td>
      <td>
        <%= link_to "<span class='glyphicon glyphicon-eye-open'></span".html_safe, profile_path(profile), class: 'btn btn-default' %>
        <%= link_to "<span class='glyphicon glyphicon-edit'></span".html_safe, edit_profile_path(profile), class: 'btn btn-default' %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/profiles/new.html.erb
<%= render 'form' %>

app/views/profiles/show.html.erb
<h2><%= @profile.name %></h2>

<h3><span class="glyphicon glyphicon-th-list"></span> History Backup</h3>

<table class="table table-condensed">
  <thead>
    <tr>
      <th width="10%">No</th>
      <th>New File(s)</th>
      <th>Updated File(s)</th>
      <th>Backup Time</th>
    </tr>
  </thead>
  <tbody>
    <% @profile.profile_details.each_with_index do |detail, index| %>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= detail.new_files %></td>
      <td><%= detail.updated_files %></td>
      <td><%= detail.created_at.strftime("%d %b %Y - %I:%M %p") %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<br/>
<h3><span class="glyphicon glyphicon-hdd"></span> Browse all file(s)</h3>
<table class="table table-condensed">
  <thead>
    <tr>
      <th width="10%">No</th>
      <th>Filename</th>
      <th>Size</th>
      <th>Modified Time</th>
      <th>Original Path</th>
      <th>Version(s)</th>
    </tr>
  </thead>
  <tbody>
    <% @profile.backup_files.order(:id).each_with_index do |file, index| %>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= File.basename(file.file.path) %></td>
      <td><%= number_to_human_size(File.stat(file.file.path).size) %></td>
      <td><%= File.stat(file.file.path).mtime.strftime("%d %b %Y - %I:%M %p") %></td>
      <td><%= file.file_url %></td>
      <td>
        <% file.versions.order(:id).each_with_index do |version, index| %>
          <%= link_to "Version #{index + 1}", download_file_profiles_path(id: version.id), {target: '_blank'} %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>